apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-poc-api-helm.fullname" . | quote }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "python-poc-api-helm.name" . | quote }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
