apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: ghcr.io/paulmarsicloud/python-api-poc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
