image:
  repository: ghcr.io/paulmarsicloud/python-api-poc-helm
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /terms
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /terms
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5

prometheus:
  server:
    enabled: true
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false

grafana:
  enabled: true
  adminPassword: admin
  service:
    type: ClusterIP
  persistence:
    enabled: false
